# Generated by Django 5.1.4 on 2024-12-24 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mention',
            name='mentioned_user',
        ),
        migrations.AddField(
            model_name='mention',
            name='mentioned_user',
            field=models.ManyToManyField(related_name='mentions_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
