# Generated by Django 5.1.4 on 2024-12-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_assigned_to_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
    ]
